title: "Annabelle Johnstone — Engineering Projects"
description: "Portfolio of university and personal engineering projects (Mechanical & Electrical Engineering at the University of Edinburgh)"
author: "Annabelle Johnstone"

markdown: kramdown
theme: minima

baseurl: "/AJengineering-projects"
url: "https://annabellejohnstone.github.io"

# Header navigation bar pages
header_pages:
  - about.md
  - university-projects.md
  - internships.md
  - home-projects.md
  - catharinas-closet.md

github_username: AnnabelleJohnstone
linkedin_username: annabelle-johnstone

collections:
  projects:
    output: true

permalink: pretty
